# coding:utf-8
conf ={}
conf['mongohost'] = "192.168.1.138"
conf['mongoport'] = 27017
conf['redishost'] = "192.168.1.138"
conf['redisport'] = 6379
conf['hostapdlog'] = "/home/hostapd.log"
conf['dhcplog'] = "/home/dhcp.log"
conf['terminal'] = "/home/terminal.log"
conf['Jan'] = 1
conf['Feb'] = 2
conf['Mar'] = 3
conf['Apr'] = 4
conf['May'] = 5
conf['Jun'] = 6
conf['Jul'] = 7
conf['Aug'] = 8
conf['Sep'] = 9
conf['Oct'] = 10
conf['Nov'] = 11
conf['Dec'] = 12